services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gimnasio
      POSTGRES_USER: admin_usuario
      POSTGRES_PASSWORD: Hola.203040
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  web:
    build: .
    command: >
      bash -c "pip install -r requirements.txt 
      && python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py collectstatic --noinput 
      && python superuser.py 
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network


  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
