
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gimnasio
      POSTGRES_USER: admin_usuario
      POSTGRES_PASSWORD: Hola.203040
    networks:
      - app-network

  web:
    build: .
    command: >
      bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
