# Generated by Django 4.2.3 on 2024-07-11 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_membresia', models.CharField(blank=True, max_length=50)),
                ('estado_pago', models.CharField(choices=[('exitoso', 'Exitoso'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido')], default='pendiente', max_length=20)),
                ('transacciones', models.ManyToManyField(blank=True, related_name='suscripciones', to='subscripciones.transaccionpago')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
